Repository solidusio/solidus_dev_support, pull requests merged in 2020-06, with the labels that each got.

#117 Fix formatting typo in readme
  lib/solidus_dev_support/templates/extension/README.md
Labels: bug

#112 Get Mergify to enforce the presence of a changelog label on PRs
  .mergify.yml
Labels: infrastructure

#118 Remove deprecated bin/r and bin/sandbox_rails binaries
  lib/solidus_dev_support/templates/extension/bin/r
  lib/solidus_dev_support/templates/extension/bin/sandbox_rails
Labels: removed

#122 Readme fixes
  lib/solidus_dev_support/templates/extension/README.md
Labels: enhancement
