Repository solidusio/solidus_dev_support, pull requests merged in 2020-10, with the labels that each got.

#150 Move generated factories to `testing_support/`
  lib/solidus_dev_support/templates/extension/lib/%file_name%/testing_support/factories.rb.tt
  lib/solidus_dev_support/templates/extension/spec/spec_helper.rb.tt
Labels: enhancement

#151 Add standard github_changelog_generator configuration
  lib/solidus_dev_support/extension.rb
  lib/solidus_dev_support/templates/extension/github_changelog_generator
Labels: enhancement

#149 Add extension configuration boilerplate
  lib/solidus_dev_support/templates/extension/lib/%file_name%.rb.tt
  lib/solidus_dev_support/templates/extension/lib/%file_name%/configuration.rb.tt
  lib/solidus_dev_support/templates/extension/lib/generators/%file_name%/install/install_generator.rb.tt
  lib/solidus_dev_support/templates/extension/lib/generators/%file_name%/install/templates/initializer.rb.tt
Labels: enhancement

#152 require webdrivers
  lib/solidus_dev_support/rspec/capybara.rb
Labels: bug

#157 Refer to Solidus wiki page for gem release info
  lib/solidus_dev_support/templates/extension/README.md
Labels: documentation

#156 Upgrade to RuboCop 1.0
  lib/solidus_dev_support/templates/extension/rubocop.yml
  solidus_dev_support.gemspec
Labels: enhancement
