Repository solidusio/solidus_dev_support, pull requests merged in 2020-09, with the labels that each got.

#135 Fix missing backslash in solidus install command
  lib/solidus_dev_support/templates/extension/bin/sandbox.tt
Labels: bug

#137 Add the approximate recommendation for dev-support to the gemspec
  lib/solidus_dev_support/templates/extension/extension.gemspec.tt
  lib/solidus_dev_support/version.rb
Labels: enhancement

#136 Switch the JS driver to WebDriver/Selenium
  lib/solidus_dev_support/rspec/capybara.rb
  lib/solidus_dev_support/rspec/feature_helper.rb
  solidus_dev_support.gemspec
Labels: breaking, bug

#141 fix capybara driver declaration
  lib/solidus_dev_support/rspec/capybara.rb
Labels: needs changelog label

#142 Fix build timeout on ci
  .circleci/config.yml
  spec/features/create_extension_spec.rb
Labels: infrastructure

#138 Bump RuboCop to latest 0.90.0 version
  solidus_dev_support.gemspec
Labels: bug

#139 Don't forcefully close issues via stale-bot
  lib/solidus_dev_support/templates/extension/.github/stale.yml
Labels: enhancement

#143 Enable new RuboCop cops automatically
  lib/solidus_dev_support/rubocop/config.yml
Labels: enhancement

#144 Fix gem_version not being found during extension generation
  lib/solidus_dev_support/extension.rb
Labels: bug

#148 Fix `NewCops: Enable` option for RuboCop
  lib/solidus_dev_support/rubocop/config.yml
  lib/solidus_dev_support/templates/extension/rubocop.yml
Labels: bug
