Repository solidusio/solidus_dev_support, pull requests merged in 2020-08, with the labels that each got.

#127 Run extension generator in sandbox
  lib/solidus_dev_support/rspec/feature_helper.rb
  lib/solidus_dev_support/templates/extension/bin/sandbox.tt
  lib/solidus_dev_support/templates/extension/spec/spec_helper.rb.tt
Labels: bug

#128 Add Changelog Rake task
  lib/solidus_dev_support/rake_tasks.rb
Labels: enhancement

#131 Don't install a payment-method in the sandbox
  lib/solidus_dev_support/templates/extension/bin/sandbox.tt
Labels: bug

#132 Add precompiled badges fro CI and coverage
  README.md
  lib/solidus_dev_support/templates/extension/README.md
Labels: enhancement

#134 Add a changelog generator config
  CHANGELOG.md
  Rakefile
  lib/solidus_dev_support/templates/extension/README.md
Labels: infrastructure

#133 Let the extension name include spaces
  lib/solidus_dev_support/templates/extension/README.md
Labels: enhancement
