Repository solidusio/solidus_dev_support, pull requests merged in 2021-02, with the labels that each got.

#167 Rename spree:install to solidus:install in the sandbox template
  lib/solidus_dev_support/templates/extension/bin/sandbox.tt
Labels: needs changelog label

#169 Fix loading factories in extensions after the last changes in Solidus
  lib/solidus_dev_support/testing_support/factories.rb
Labels: bug

#170 Fix factories loading, part 2
  lib/solidus_dev_support/testing_support/factories.rb
Labels: bug

#171 Explode directories into individual files
  lib/solidus_dev_support/testing_support/factories.rb
Labels: bug

#172 Add instruction on how to use the new factories in apps
  lib/solidus_dev_support/templates/extension/README.md
Labels: enhancement
