Repository solidusio/solidus_dev_support, pull requests merged in 2023-05, with the labels that each got.

#205 Remove support for deprecated way of loading factories
  .circleci/config.yml
  .rubocop.yml
  lib/solidus_dev_support/rubocop.rb
  lib/solidus_dev_support/templates/extension/README.md
  lib/solidus_dev_support/templates/extension/spec/spec_helper.rb.tt
  lib/solidus_dev_support/testing_support/factories.rb
  spec/features/create_extension_spec.rb
Labels: breaking, needs changelog label

#206 Update release-related files
  CHANGELOG.md
  OLD_CHANGELOG.md
  Rakefile
  solidus_dev_support.gemspec
Labels: enhancement

#204 Adapt to latest Solidus release
  .circleci/config.yml
  Gemfile
  README.md
  lib/solidus_dev_support/templates/extension/.circleci/config.yml
  lib/solidus_dev_support/templates/extension/Gemfile.tt
  lib/solidus_dev_support/templates/extension/bin/sandbox.tt
  lib/solidus_dev_support/templates/extension/extension.gemspec.tt
Labels: infrastructure

#209 Follow the new release process for extension template
  lib/solidus_dev_support/templates/extension/CHANGELOG.md
  lib/solidus_dev_support/templates/extension/CHANGELOG.md.tt
  lib/solidus_dev_support/templates/extension/Rakefile
Labels: enhancement
