Repository solidusio/solidus_dev_support, pull requests merged in 2024-12, with the labels that each got.

#223 Fix(specs): Correct path for gem in spec
  lib/solidus_dev_support/templates/extension/bin/sandbox.tt
  spec/features/create_extension_spec.rb
Labels: infrastructure

#222 Allow passing a user class to the test app generator
  lib/solidus_dev_support/rake_tasks.rb
  lib/solidus_dev_support/templates/extension/Rakefile
Labels: enhancement

#224 Extension generator: Do not always require solidus_auth_devise
  lib/solidus_dev_support/templates/extension/Gemfile.tt
  lib/solidus_dev_support/templates/extension/Rakefile
Labels: enhancement

#225 Use at least solidus_support 0.12.0
  lib/solidus_dev_support/templates/extension/extension.gemspec.tt
Labels: needs changelog label
